<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xlink="http://www.w3.org/1999/xlink">





    <xsl:output method="xml" indent="yes"/>

    <xsl:template match="/">
        <xsl:element name="collection">
            <xsl:for-each select="/collection/record">
                <xsl:element name="journal">
                    <xsl:attribute name="issn"><xsl:value-of select="datafield[@tag='022']/subfield[@code='a']"></xsl:value-of></xsl:attribute>
                    <xsl:variable name="subcategory" select="datafield[@tag='650']/subfield[@code='x']"></xsl:variable>

                    <xsl:variable name="cdu">
                        <xsl:choose>
                            <xsl:when test="$subcategory='Allergy'">61</xsl:when>)
                            <xsl:when test="$subcategory='Alternative Medicine'">61</xsl:when>)
                            <xsl:when test="$subcategory='Anatomy'">61</xsl:when>)
                            <xsl:when test="$subcategory='Andrology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Anesthesiology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Cardiology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Cerebrovascular Diseases  &amp; Stroke'">61</xsl:when>)
                            <xsl:when test="$subcategory='Clinical Medicine'">61</xsl:when>)
                            <xsl:when test="$subcategory='Dentistry'">61</xsl:when>)
                            <xsl:when test="$subcategory='Dermatology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Diabetes and Hypertension'">61</xsl:when>)
                            <xsl:when test="$subcategory='Diagnostics'">61</xsl:when>)
                            <xsl:when test="$subcategory='Diseases'">61</xsl:when>)
                            <xsl:when test="$subcategory='Ear, Nose &amp; Throat'">61</xsl:when>)
                            <xsl:when test="$subcategory='Embryology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Emergency Medicine and Critical Care'">61</xsl:when>)
                            <xsl:when test="$subcategory='Endocrinology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Family Medicine'">61</xsl:when>)
                            <xsl:when test="$subcategory='Forensic Science'">61</xsl:when>)
                            <xsl:when test="$subcategory='Gastroenterology'">61</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">61</xsl:when>)
                            <xsl:when test="$subcategory='Genetics'">61</xsl:when>)
                            <xsl:when test="$subcategory='Geriatrics'">61</xsl:when>)
                            <xsl:when test="$subcategory='Hematology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Hepatology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Histology'">61</xsl:when>)
                            <xsl:when test="$subcategory='HIV &amp; AIDS'">61</xsl:when>)
                            <xsl:when test="$subcategory='Immunology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Legal Medicine'">61</xsl:when>)
                            <xsl:when test="$subcategory='Medical Education, Training &amp; Research'">61</xsl:when>)
                            <xsl:when test="$subcategory='Medical Informatics'">61</xsl:when>)
                            <xsl:when test="$subcategory='Medical Specialties'">61</xsl:when>)
                            <xsl:when test="$subcategory='Medicinal Chemistry'">61</xsl:when>)
                            <xsl:when test="$subcategory='Metabolism'">61</xsl:when>)
                            <xsl:when test="$subcategory='Morphology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Neurology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Nuclear Medicine'">61</xsl:when>)
                            <xsl:when test="$subcategory='Nursing'">61</xsl:when>)
                            <xsl:when test="$subcategory='Nutrition and Dietetics'">61</xsl:when>)
                            <xsl:when test="$subcategory='Obstetrics and Gynecology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Oncology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Ophthalmology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Orthopaedics'">61</xsl:when>)
                            <xsl:when test="$subcategory='Pathology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Pediatrics'">61</xsl:when>)
                            <xsl:when test="$subcategory='Pharmacy and Pharmacology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Physiology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Physiotherapy'">61</xsl:when>)
                            <xsl:when test="$subcategory='Preventive Medicine'">61</xsl:when>)
                            <xsl:when test="$subcategory='Psychiatry &amp; Psychology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Public health'">61</xsl:when>)
                            <xsl:when test="$subcategory='Radiology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Reproduction &amp; Reproductive Medicine'">61</xsl:when>)
                            <xsl:when test="$subcategory='Rheumatology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Sports medicine'">61</xsl:when>)
                            <xsl:when test="$subcategory='Surgery'">61</xsl:when>)
                            <xsl:when test="$subcategory='Therapeutics'">61</xsl:when>)
                            <xsl:when test="$subcategory='Toxicology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Tuberculosis'">61</xsl:when>)
                            <xsl:when test="$subcategory='Urology and Nephrology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Venereology'">61</xsl:when>)
                            <xsl:when test="$subcategory='Veterinary Science'">61</xsl:when>)
                            <xsl:when test="$subcategory='Architecture, Fine and Decorative Arts'">72</xsl:when>)
                            <xsl:when test="$subcategory='Current Events &amp; News'">7</xsl:when>)
                            <xsl:when test="$subcategory='Education &amp; Careers'">7</xsl:when>)
                            <xsl:when test="$subcategory='Fashion &amp; Entertainment'">7</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">7</xsl:when>)
                            <xsl:when test="$subcategory='History'">93/94</xsl:when>)
                            <xsl:when test="$subcategory='Language &amp; Linguistics'">81</xsl:when>)
                            <xsl:when test="$subcategory='Literature'">82</xsl:when>)
                            <xsl:when test="$subcategory='Performing Arts, Travel and Leisure'">7</xsl:when>)
                            <xsl:when test="$subcategory='Philosophy'">1</xsl:when>)
                            <xsl:when test="$subcategory='Religion'">2</xsl:when>)
                            <xsl:when test="$subcategory='Society and Culture'">3</xsl:when>)
                            <xsl:when test="$subcategory='Aerospace and Aeronautics'">52</xsl:when>)
                            <xsl:when test="$subcategory='Agricultural Engineering'">63</xsl:when>)
                            <xsl:when test="$subcategory='Architecture'">72</xsl:when>)
                            <xsl:when test="$subcategory='Automobile and Transportation'">6</xsl:when>)
                            <xsl:when test="$subcategory='Biomedical Engineering'">60</xsl:when>)
                            <xsl:when test="$subcategory='Biotechnology'">60</xsl:when>)
                            <xsl:when test="$subcategory='Chemical Engineering'">54</xsl:when>)
                            <xsl:when test="$subcategory='Civil Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Control Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Cryotechnology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Dairy Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Electrical Engineering'">621.3</xsl:when>)
                            <xsl:when test="$subcategory='Electronics'">621.3</xsl:when>)
                            <xsl:when test="$subcategory='Energy Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Environmental Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Ergonomics'">6</xsl:when>)
                            <xsl:when test="$subcategory='Fire Fighting and Safety Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Fluid Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Food Science and Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Fuel Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">6</xsl:when>)
                            <xsl:when test="$subcategory='Industrial Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Instrumentation'">6</xsl:when>)
                            <xsl:when test="$subcategory='Marine Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Mechanical Engineering'">621.01</xsl:when>)
                            <xsl:when test="$subcategory='Metrology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Mining Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Nuclear Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Petroleum Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Pharmaceutical Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Polymer Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Printing Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Production Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Quality Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Satellites, Space Probes &amp; Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Textile Engineering'">6</xsl:when>)
                            <xsl:when test="$subcategory='Biomaterials'">6</xsl:when>)
                            <xsl:when test="$subcategory='Ceramics'">6</xsl:when>)
                            <xsl:when test="$subcategory='Coatings and Films'">6</xsl:when>)
                            <xsl:when test="$subcategory='Composites'">6</xsl:when>)
                            <xsl:when test="$subcategory='Corrosion'">6</xsl:when>)
                            <xsl:when test="$subcategory='Extractive Metallurgy'">6</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">6</xsl:when>)
                            <xsl:when test="$subcategory='Melting, Coating, Powder Metallurgy'">6</xsl:when>)
                            <xsl:when test="$subcategory='Metals, Minerals, Ores &amp; Alloys'">6</xsl:when>)
                            <xsl:when test="$subcategory='Nanomaterials'">6</xsl:when>)
                            <xsl:when test="$subcategory='Packaging Materials &amp; Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Physical Metallurgy'">6</xsl:when>)
                            <xsl:when test="$subcategory='Rubber Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Super Conductors'">6</xsl:when>)
                            <xsl:when test="$subcategory='Textile materials'">6</xsl:when>)
                            <xsl:when test="$subcategory='Treatment &amp; Finishing'">6</xsl:when>)
                            <xsl:when test="$subcategory='Wood, Paper &amp; Cellulosics'">6</xsl:when>)
                            <xsl:when test="$subcategory='Working, Forming, Machining &amp; Joining'">6</xsl:when>)
                            <xsl:when test="$subcategory='Atmospheric Science'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Biodiversity'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Biomass Energy &amp; Biofuels'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Conservation'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Desert Ecology &amp; Desertification'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Ecosystems &amp; Ecology'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Ecotoxicology'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Energy Conservation &amp; Alternate Energy Sources'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Environmental Engineering'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Environmental laws'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Environmental Planning &amp; Studies'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Global Warming'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Hazardous Substance Handling, Management &amp; Disposal'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Natural Disasters &amp; Industrial Accidents'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Occupational Hazards &amp; Health'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Pollution (Air, Noise, Soil and Water) &amp; Control'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Radioactivity &amp; nuclear fallout'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Sustainable Development'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Waste management and Recycling'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Agricultural Biotechnology'">63</xsl:when>)
                            <xsl:when test="$subcategory='Agricultural Engineering'">63</xsl:when>)
                            <xsl:when test="$subcategory='Agro Business, Economics and Policies'">63</xsl:when>)
                            <xsl:when test="$subcategory='Agronomy'">63</xsl:when>)
                            <xsl:when test="$subcategory='Animal Husbandry, Livestock Management &amp; Poultry Sciences'">63</xsl:when>)
                            <xsl:when test="$subcategory='Animal Nutrition,  Feed, Feed Additives &amp; Manufacture'">63</xsl:when>)
                            <xsl:when test="$subcategory='Apiculture'">63</xsl:when>)
                            <xsl:when test="$subcategory='Crops, Crop Production and Protection'">63</xsl:when>)
                            <xsl:when test="$subcategory='Dairy Technology'">63</xsl:when>)
                            <xsl:when test="$subcategory='Dryland Farming'">63</xsl:when>)
                            <xsl:when test="$subcategory='Fisheries and Aquaculture'">63</xsl:when>)
                            <xsl:when test="$subcategory='Food Science and Technology'">63</xsl:when>)
                            <xsl:when test="$subcategory='Forestry'">63</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">63</xsl:when>)
                            <xsl:when test="$subcategory='Horticulture and Plant Culture (including Arboriculture)'">63</xsl:when>)
                            <xsl:when test="$subcategory='Organic Farming, Rural Development, Sustainable Agriculture'">63</xsl:when>)
                            <xsl:when test="$subcategory='Pests,  Pest Control &amp; Integrated Pest Management'">63</xsl:when>)
                            <xsl:when test="$subcategory='Plant Breeding'">63</xsl:when>)
                            <xsl:when test="$subcategory='Plant Pathology'">63</xsl:when>)
                            <xsl:when test="$subcategory='Post Harvesting Operations and Storage'">63</xsl:when>)
                            <xsl:when test="$subcategory='Seed Technology &amp; Propagation'">63</xsl:when>)
                            <xsl:when test="$subcategory='Soil Chemistry, Microbiology, Fertility &amp; Fertilizers'">63</xsl:when>)
                            <xsl:when test="$subcategory='Veterinary Science'">63</xsl:when>)
                            <xsl:when test="$subcategory='Water and Water Resources'">63</xsl:when>)
                            <xsl:when test="$subcategory='Cartography'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Energy Minerals'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Engineering Geology'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Environmental Geology'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Extraterrestrial Geology'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Geochemistry'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Geographic Information Systems &amp; Remote Sensing'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Geography'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Geology'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Geophysics'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Hydrology'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Marine Geology and Oceanography'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Meteorology'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Mineralogy'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Paleontology'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Petrology'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Stratigraphy'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Tectonics, Seismology &amp; Volcanology'">55/56</xsl:when>)
                            <xsl:when test="$subcategory='Analytical Chemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Applied Chemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Biochemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Chemical Engineering'">54</xsl:when>)
                            <xsl:when test="$subcategory='Clinical Chemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Crystallography'">54</xsl:when>)
                            <xsl:when test="$subcategory='Electrochemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Environmental Chemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">54</xsl:when>)
                            <xsl:when test="$subcategory='Inorganic Chemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Kinetics'">54</xsl:when>)
                            <xsl:when test="$subcategory='Medicinal Chemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Nuclear Chemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Organic Chemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Petroleum'">54</xsl:when>)
                            <xsl:when test="$subcategory='Pharmaceutical Chemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Physical Chemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Polymers and Plastics'">54</xsl:when>)
                            <xsl:when test="$subcategory='Radiation Chemistry'">54</xsl:when>)
                            <xsl:when test="$subcategory='Synthesis'">54</xsl:when>)
                            <xsl:when test="$subcategory='Toxicology'">54</xsl:when>)
                            <xsl:when test="$subcategory='Artificial Intelligence'">004</xsl:when>)
                            <xsl:when test="$subcategory='Automation'">004</xsl:when>)
                            <xsl:when test="$subcategory='Computational Biosciences'">004</xsl:when>)
                            <xsl:when test="$subcategory='Computer Aided Design &amp; Production Control'">004</xsl:when>)
                            <xsl:when test="$subcategory='Computer Architecture, Languages and Compilers'">004</xsl:when>)
                            <xsl:when test="$subcategory='Computer Science (Hardware &amp; Networks)'">004</xsl:when>)
                            <xsl:when test="$subcategory='Computer Security Confidentiality'">004</xsl:when>)
                            <xsl:when test="$subcategory='Cybernetics'">004</xsl:when>)
                            <xsl:when test="$subcategory='Data Storage and Data Mining'">004</xsl:when>)
                            <xsl:when test="$subcategory='Database Design &amp; Management'">004</xsl:when>)
                            <xsl:when test="$subcategory='Embedded Systems'">004</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">004</xsl:when>)
                            <xsl:when test="$subcategory='Graphics'">004</xsl:when>)
                            <xsl:when test="$subcategory='Healthcare Database &amp; Medical Informatics'">004</xsl:when>)
                            <xsl:when test="$subcategory='Information Extraction, Retrieval and Filtering'">004</xsl:when>)
                            <xsl:when test="$subcategory='Information Science and Systems'">004</xsl:when>)
                            <xsl:when test="$subcategory='Insurance Financial Systems'">004</xsl:when>)
                            <xsl:when test="$subcategory='Internet'">004</xsl:when>)
                            <xsl:when test="$subcategory='Mobile Computing'">004</xsl:when>)
                            <xsl:when test="$subcategory='Modelling &amp; Simulation'">004</xsl:when>)
                            <xsl:when test="$subcategory='Multimedia'">004</xsl:when>)
                            <xsl:when test="$subcategory='Neural Networks'">004</xsl:when>)
                            <xsl:when test="$subcategory='Robotics'">004</xsl:when>)
                            <xsl:when test="$subcategory='Software Engineering'">004</xsl:when>)
                            <xsl:when test="$subcategory='Web Development'">004</xsl:when>)
                            <xsl:when test="$subcategory='Algebra'">51</xsl:when>)
                            <xsl:when test="$subcategory='Algebraic Geometry'">51</xsl:when>)
                            <xsl:when test="$subcategory='Algorithms'">51</xsl:when>)
                            <xsl:when test="$subcategory='Applied Mathematics'">51</xsl:when>)
                            <xsl:when test="$subcategory='Arithmetic'">51</xsl:when>)
                            <xsl:when test="$subcategory='Calculus'">51</xsl:when>)
                            <xsl:when test="$subcategory='Combinatorics'">51</xsl:when>)
                            <xsl:when test="$subcategory='Complex Analysis'">51</xsl:when>)
                            <xsl:when test="$subcategory='Differential Geometry'">51</xsl:when>)
                            <xsl:when test="$subcategory='Game Theory'">51</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">51</xsl:when>)
                            <xsl:when test="$subcategory='Geometry'">51</xsl:when>)
                            <xsl:when test="$subcategory='Graph Theory'">51</xsl:when>)
                            <xsl:when test="$subcategory='Group theory'">51</xsl:when>)
                            <xsl:when test="$subcategory='Logic'">51</xsl:when>)
                            <xsl:when test="$subcategory='Mathematical Analysis &amp; Logic'">51</xsl:when>)
                            <xsl:when test="$subcategory='Mathematical Physics'">51</xsl:when>)
                            <xsl:when test="$subcategory='Number Theory'">51</xsl:when>)
                            <xsl:when test="$subcategory='Numerical Analysis'">51</xsl:when>)
                            <xsl:when test="$subcategory='Probability'">51</xsl:when>)
                            <xsl:when test="$subcategory='Set Theory'">51</xsl:when>)
                            <xsl:when test="$subcategory='Statistics'">51</xsl:when>)
                            <xsl:when test="$subcategory='Stochastic Computation'">51</xsl:when>)
                            <xsl:when test="$subcategory='Topology'">51</xsl:when>)
                            <xsl:when test="$subcategory='Anthropology'">3</xsl:when>)
                            <xsl:when test="$subcategory='Archeology'">3</xsl:when>)
                            <xsl:when test="$subcategory='Behavioral Science (Psychology) and Counselling'">3</xsl:when>)
                            <xsl:when test="$subcategory='Communities and Urban Planning'">3</xsl:when>)
                            <xsl:when test="$subcategory='Community Based Awareness and Relief Service'">3</xsl:when>)
                            <xsl:when test="$subcategory='Demographic Studies'">3</xsl:when>)
                            <xsl:when test="$subcategory='Developmental Issues &amp; Socioeconomic Studies'">3</xsl:when>)
                            <xsl:when test="$subcategory='Disability Studies &amp; Assistance'">3</xsl:when>)
                            <xsl:when test="$subcategory='Foreign Policy, Defense and Internal Security'">3</xsl:when>)
                            <xsl:when test="$subcategory='Gender Studies'">3</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">3</xsl:when>)
                            <xsl:when test="$subcategory='Journalism, Mass Communication, Media &amp; Publishing'">3</xsl:when>)
                            <xsl:when test="$subcategory='Museums &amp; Heritage Organizations'">3</xsl:when>)
                            <xsl:when test="$subcategory='Political Science'">3</xsl:when>)
                            <xsl:when test="$subcategory='Public Policy &amp; Administration'">3</xsl:when>)
                            <xsl:when test="$subcategory='Regional and International Studies'">3</xsl:when>)
                            <xsl:when test="$subcategory='Rehabilitation'">3</xsl:when>)
                            <xsl:when test="$subcategory='Sociology'">3</xsl:when>)
                            <xsl:when test="$subcategory='Andrology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Animal Physiology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Biochemistry'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Bioinformatics'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Biology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Biophysics'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Biotechnology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Botany'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Computational Biosciences'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Cytology, Cell Biology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Entomology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Ethology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Evolutionary Studies'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Genetics'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Genomics'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Immunology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Limnology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Metabolism'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Micro and Molecular Biology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Mineralogy'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Morphology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Ornithology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Palaeontology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Taxonomy &amp; Systematics'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Toxicology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Virology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Zoology'">57/59</xsl:when>)
                            <xsl:when test="$subcategory='Accounting and Auditing'">33</xsl:when>)
                            <xsl:when test="$subcategory='Actuarial Science, Insurance and Risk Management'">33</xsl:when>)
                            <xsl:when test="$subcategory='Business Management'">33</xsl:when>)
                            <xsl:when test="$subcategory='E-Commerce'">33</xsl:when>)
                            <xsl:when test="$subcategory='Economics'">33</xsl:when>)
                            <xsl:when test="$subcategory='Finance'">33</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">33</xsl:when>)
                            <xsl:when test="$subcategory='Insurance and Investment'">33</xsl:when>)
                            <xsl:when test="$subcategory='International Business &amp; Transnational Corporations'">33</xsl:when>)
                            <xsl:when test="$subcategory='Marketing and Sales'">33</xsl:when>)
                            <xsl:when test="$subcategory='Material &amp; Supply Chain Management'">33</xsl:when>)
                            <xsl:when test="$subcategory='Multimodal Transport &amp; Logistics'">33</xsl:when>)
                            <xsl:when test="$subcategory='Operations Research'">33</xsl:when>)
                            <xsl:when test="$subcategory='Organizational change and Development'">33</xsl:when>)
                            <xsl:when test="$subcategory='Organizational Communication, Business Writing'">33</xsl:when>)
                            <xsl:when test="$subcategory='Organizational Psychology'">33</xsl:when>)
                            <xsl:when test="$subcategory='Personnel Management &amp; Training'">33</xsl:when>)
                            <xsl:when test="$subcategory='Projects and Consultancies'">33</xsl:when>)
                            <xsl:when test="$subcategory='Public Relations'">33</xsl:when>)
                            <xsl:when test="$subcategory='Quality Management'">33</xsl:when>)
                            <xsl:when test="$subcategory='Stocks and Shares'">33</xsl:when>)
                            <xsl:when test="$subcategory='Strategic Management &amp; Business Policy'">33</xsl:when>)
                            <xsl:when test="$subcategory='Trade and Commerce'">33</xsl:when>)
                            <xsl:when test="$subcategory='Arbitration, Education &amp; Training'">34</xsl:when>)
                            <xsl:when test="$subcategory='Banking Law'">34</xsl:when>)
                            <xsl:when test="$subcategory='Constitution and Judicial System'">34</xsl:when>)
                            <xsl:when test="$subcategory='Corporate laws'">34</xsl:when>)
                            <xsl:when test="$subcategory='Crime, Criminology and Law Enforcement'">34</xsl:when>)
                            <xsl:when test="$subcategory='Domicile and Immigration Laws'">34</xsl:when>)
                            <xsl:when test="$subcategory='Environmental Law &amp; Policy'">34</xsl:when>)
                            <xsl:when test="$subcategory='Foreign Trade &amp; Commercial Transactions'">34</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">34</xsl:when>)
                            <xsl:when test="$subcategory='Industrial Relations Law'">34</xsl:when>)
                            <xsl:when test="$subcategory='Insurance Law'">34</xsl:when>)
                            <xsl:when test="$subcategory='Intellectual Property'">34</xsl:when>)
                            <xsl:when test="$subcategory='Investment Laws'">34</xsl:when>)
                            <xsl:when test="$subcategory='Policies'">34</xsl:when>)
                            <xsl:when test="$subcategory='Regional and International Law'">34</xsl:when>)
                            <xsl:when test="$subcategory='Taxation Laws'">34</xsl:when>)
                            <xsl:when test="$subcategory='Cables &amp; Optical Fibres'">6</xsl:when>)
                            <xsl:when test="$subcategory='Communication Networks &amp; Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Digital Signal Processing'">6</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">6</xsl:when>)
                            <xsl:when test="$subcategory='Image Processing &amp; Television Technology'">6</xsl:when>)
                            <xsl:when test="$subcategory='Telemedicine'">6</xsl:when>)
                            <xsl:when test="$subcategory='Wireless Communications'">6</xsl:when>)
                            <xsl:when test="$subcategory='Abstracting and Indexing'">02</xsl:when>)
                            <xsl:when test="$subcategory='Acquisition'">02</xsl:when>)
                            <xsl:when test="$subcategory='Archives &amp;  Preservation'">02</xsl:when>)
                            <xsl:when test="$subcategory='Cataloging'">02</xsl:when>)
                            <xsl:when test="$subcategory='Classification'">02</xsl:when>)
                            <xsl:when test="$subcategory='Digital Libraries'">02</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">02</xsl:when>)
                            <xsl:when test="$subcategory='Information Sources, Services and Retrieval'">02</xsl:when>)
                            <xsl:when test="$subcategory='Librarianship and Libraries'">02</xsl:when>)
                            <xsl:when test="$subcategory='Library Automation'">02</xsl:when>)
                            <xsl:when test="$subcategory='Library Management'">02</xsl:when>)
                            <xsl:when test="$subcategory='Library Networks'">02</xsl:when>)
                            <xsl:when test="$subcategory='Serials Control'">02</xsl:when>)
                            <xsl:when test="$subcategory='Acoustics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Applied Physics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Astronomy'">53</xsl:when>)
                            <xsl:when test="$subcategory='Astrophysics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Atmospheric Physics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Condensed Matter Physics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Cryogenics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Energy'">53</xsl:when>)
                            <xsl:when test="$subcategory='General and Others'">53</xsl:when>)
                            <xsl:when test="$subcategory='Magnetism'">53</xsl:when>)
                            <xsl:when test="$subcategory='Mechanics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Nuclear Physics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Optics &amp; Opto Electronics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Particle Physics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Plasma Physics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Radiation'">53</xsl:when>)
                            <xsl:when test="$subcategory='Relativity'">53</xsl:when>)
                            <xsl:when test="$subcategory='Solid State Physics'">53</xsl:when>)
                            <xsl:when test="$subcategory='Thermodynamics and Heat Transfer'">53</xsl:when>)
                            <xsl:when test="$subcategory='Ultrasonic'">53</xsl:when>)

                        </xsl:choose>
                    </xsl:variable>
                    <xsl:if test="string-length($cdu)&gt;0">
                        <xsl:element name="cdu"><xsl:value-of select="$cdu"></xsl:value-of></xsl:element>
                    </xsl:if>
                </xsl:element>
            </xsl:for-each>
        </xsl:element>
    </xsl:template>









</xsl:stylesheet>